on: [push]

jobs:
  boman_scan:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Boman
        run: |
          sudo pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat==0.8
          sudo boman-cli
